### ISSUE TITLE
Screenshots not going to clipboard

### ISSUE THREAD

**Issue by Skawtrs** [Blackberry0Pie/CoX-Scouter-External#2]
If you set the hotkey to say 's', you can no longer type 's' in game, however, it doesn't seem to copy any sort of screenshot to your clipboard and I do not see anything in any runelite folders where the screenshot was saved.

**Comment by Blackberry0Pie** [comment]
Maybe don't do that. Or set it to a _modifier key_ + 's' eg "ctrl + s".

**Comment by Skawtrs** [comment]
...Right, but again, ctrl+s doesn't copy a screenshot to clipboard.

**Comment by Skawtrs** [comment]
No matter the key combo, nothing gets copied to clipboard.

**Comment by Skawtrs** [comment]
That was simply an example. Letting you know it's doing something, but not copying anything to clipboard.

**Comment by Blackberry0Pie** [comment]
I see. Both issues seem to also occurring for the standard RL plugin. Thanks for the bug report.
1) screenshot not taken:
this.client.getVar() must be called on client thread

2) screenshot hotkey consumed when screenshot not taken:
https://github.com/runelite/runelite/issues/12155

**Comment by Blackberry0Pie** [comment]
v1.2 should fix the screenshot not being taken. I'll close this issue after the changes are approved.

I'll fix the same bug as #12155 after RL fixes the default plugin.
