### ISSUE TITLE
When using recommended items, cannot differentiate "Combat unknown" from "Puzzle unknown"

### ISSUE THREAD

**Issue by TaylorAbraham** [Blackberry0Pie/CoX-Scouter-External#3]
Title. Since the recommended items interface replaces the "combat" or "puzzle" text, you just see "Unknown" and can't tell if it's a puzzle or combat unknown.

Unrelated, but something I dislike about the vanilla scouter is you can only blacklist "Unknown" as a room whereas I'd like to blacklist "Combat Unknown" but allow "Puzzle Unknown". If that could be implemented somehow (could even just be a checkbox "Blacklist combat unknown rooms"), that would be awesome :)

**Comment by Blackberry0Pie** [comment]
You actually can differentiate between unknown combat and unknown puzzle in the vanilla scouter, and therefore also in the external scouter; use "unknown (combat)" or "unknown (puzzle)".
![example](https://i.gyazo.com/b5a41445534f96c5e21cd1f3cda68a33.png)
