### ISSUE TITLE
Items not scaling down in size

### ISSUE THREAD

**Issue by usa-usa-usa-usa** [Blackberry0Pie/CoX-Scouter-External#4]
The items in my overlay are not scaling down.

https://i.imgur.com/hr1miBe.png

Here are the settings I am using:
https://i.imgur.com/qXebTKu.png

I do have the scout overlay turned off in the core plugin

**Comment by Blackberry0Pie** [comment]
Thank you for the bug report. What's happening here is that your Runelite > Overlay Settings > Interface Overlay Font is set to "Small" and my plugin currently doesn't display correctly for the small font. I'll fix it soon(tm).
