### ISSUE TITLE
New cox update broke plugin

### ISSUE THREAD

**Issue by Tolemi959** [Blackberry0Pie/CoX-Scouter-External#7]
The new cox update QoL changes broke the plugin. It doesn't properly show up when using the new reload raid feature. I don't think this plugin gets updated very often, but it's such a massively useful tool when scouting. Hoping to see it get fixed. The OSRS update can be found here: https://secure.runescape.com/m=news/chambers-of-xeric-changes?oldschool=1

**Comment by Blackberry0Pie** [comment]
Ok, I'll look into it when I can but life has been busy for me recently.

**Comment by Blackberry0Pie** [comment]
Life's better now but it looks like there may be issues cropping up with the default scouter, I'll wait for those to resolve before updating this plugin.

**Comment by Blackberry0Pie** [comment]
I think this was resolved with the Runelite plugin update and I forgot to close this
