### ISSUE TITLE
Chambers of Xeric Plugin

### ISSUE THREAD

**Issue by thefriendlydish** [Blackberry0Pie/CoX-Scouter-External#8]
For the last 24 hours I have suddenly lost access to the scouting side of the 'Chambers of Xeric' plugin and can no longer use the '!layout' command nor does the raid layout show up in chat box upon entering the raid with that add on enabled. Some feed back would be greatly appreciated as I rely completely on this part of the plugin to find raids that I am able to do.

**Comment by Blackberry0Pie** [comment]
!layout is part of the default Runelite scouter for which the proper channel for support is here: [Runelite Discord #Support](https://discord.com/channels/301497432909414422/442492468307427330)

**Comment by thefriendlydish** [comment]
> !layout is part of the default Runelite scouter for which the proper channel for support is here: [Runelite Discord #Support](https://discord.com/channels/301497432909414422/442492468307427330)

Thanks for pointing me the right way :)
